[workspace]
members = [
	"acme-ssl",
	"blog",
	"blog/hyper-staticfile",
	"experiments/linkerclient",
	"experiments/rbpf",
	"experiments/rbpf-disassemble",
	"experiments/sni-director",
	"experiments/sockets",
	"infra/cloudsafe",
	"infra/memfd",
	"infra/tokio-sendfd",
	"ksuid",
	"ksuid/cli",
	"linker",
	"parsing/tls",
	"publish-release",
	"yscloud-config-model",
]
