[workspace]
members = [
	"experiments/esockets",
	"experiments/linkerclient",
	"experiments/sni-multiplexor",
	"experiments/socket-traits",
	"experiments/sockets",
	"infra/cloudsafe",
	"infra/memfd",
	"infra/owned_fd",
	"ksuid",
	"ksuid/cli",
	"linker",
	"magnetite/bencode",
	"magnetite/magnetite-common",
	"magnetite/vfshost",
	"magnetite/webserver",
	"parsing/tls",
	"webserver",
	"yscloud-config-model",
]
