[package]
name = "yscloud-linker"
version = "0.1.3"
authors = ["Stacey Ell <stacey.ell@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32"
env_logger = "0.6"
log = "0.4"
nix = "0.13"
rand = "*"
yscloud-config-model = { path = "../yscloud-config-model" }
semver = { version = "0.9.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
signal-hook = "0.1"
sockets = { path = "../experiments/sockets" }
tempfile = "3"
users = "0.9.1"
uuid = { version = "0.6", features = ["v4", "serde"] }
# sodiumoxide = "*"
# git2 = "*"
# toml = "0.4"
