[package]
name = "blog"
version = "0.1.0"
authors = ["Stacey Ell <stacey.ell@gmail.com>"]
edition = "2018"

[dependencies]
zip = "*"
hyper-staticfile = { path = "hyper-staticfile" }
futures = "0.1.21"
http = "0.1.5"
chrono = "0.4.2"
hyper = "0.12.1"
time = "0.1"
