[package]
name = "pb-builder"
version = "0.1.0"
authors = ["Stacey Ell <stacey.ell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# tonic = "0.4.0"
# prost = "0.6.1"
tonic-build = "0.3.1"
